[features]
seeds = false
[programs.devnet]
sol_it = "C12tVda17vqMYuzEjT5NB9g4pDZeq9myejp6viPKuqsc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
